export const SHOW_ALL_LOCATIONS = "SHOW_ALL_LOCATIONS";
export const UPDATE_SPIN_STATE = "UPDATE_SPIN_STATE";

export const GET_LOCATION_RECORDS_SUCCESS = "GET_LOCATION_RECORDS_SUCCESS";
export const GET_LOCATION_RECORDS_ERROR = "GET_LOCATION_RECORDS_ERROR";
export const STORE_MAP_DATA = "STORE_MAP_DATA";

export const GET_LOCATION_DETAIL_SUCCESS = "GET_LOCATION_DETAIL_SUCCESS";
export const GET_LOCATION_DETAIL_ERROR = "GET_LOCATION_DETAIL_ERROR";
export const GET_DISTRICT_SUCCESS = "GET_DISTRICT_SUCCESS";
export const GET_DISTRICT_ERROR = "GET_DISTRICT_ERROR";
export const SET_SELECTED_CITY = "SET_SELECTED_CITY";
export const SET_SELECTED_DISTRICT = "SET_SELECTED_DISTRICT";
export const GET_DEVICE_LIST_SUCCESS = "GET_DEVICE_LIST_SUCCESS";
export const GET_DEVICE_LIST_ERROR = "GET_DEVICE_LIST_ERROR";
export const GET_LATEST_DEVICE_RECORD_SUCCESS =
  "GET_LATEST_DEVICE_RECORD_SUCCESS";
export const GET_LATEST_DEVICE_RECORD_ERROR = "GET_LATEST_DEVICE_RECORD_ERROR";
export const UPDATE_SHOW_COLOR_INDEX = "UPDATE_SHOW_COLOR_INDEX";

export const GET_CURRENT_CITY_DISTRICT_AND_NEARBY_SUCCESS =
  "GET_CURRENT_CITY_DISTRICT_AND_NEARBY_SUCCESS";
export const GET_DEVICES_IN_CURRENT_DISTRICT_SUCCESS =
  "GET_DEVICES_IN_CURRENT_DISTRICT_SUCCESS";
export const UPDATE_NEARBY_DEVICE_LATEST_RECORD =
  "UPDATE_NEARBY_DEVICE_LATEST_RECORD";
export const UPDATE_MEASUREMENT_DEVICE_LATEST_RECORD =
  "UPDATE_MEASUREMENT_DEVICE_LATEST_RECORD";
export const SHOW_HIDE_DEVICE_DETAIL = "SHOW_HIDE_DEVICE_DETAIL";
export const UPDATE_NEAREST_DEVICE_RECORD = "UPDATE_NEAREST_DEVICE_RECORD";
export const UPDATE_OTHER_DISTRICT_RECORD = "UPDATE_OTHER_DISTRICT_RECORD";
export const ADD_NEW_DEVICE = "ADD_NEW_DEVICE";
export const REMOVE_DEVICE = "REMOVE_DEVICE";
export const SWAP_DEFAULT_DEVICE = "SWAP_DEFAULT_DEVICE";
export const SAVE_MAP = "SAVE_MAP";
export const SAVE_MARKER = "SAVE_MARKER";

/** BEGIN NEARBY ACTION TYPES */

export const SAVE_OAUTH_ERROR = "SAVE_OAUTH_ERROR";
export const SAVE_OAUTH_SUCCESS = "SAVE_OAUTH_SUCCESS";
export const SAVE_OAUTH_REQUESTED = "SAVE_OAUTH_REQUESTED";
export const GET_CURRENT_CITY_DISTRICT_REQUESTED =
  "GET_CURRENT_CITY_DISTRICT_REQUESTED";
export const GET_CURRENT_CITY_DISTRICT_SUCCESS =
  "GET_CURRENT_CITY_DISTRICT_SUCCESS";
export const GET_CURRENT_CITY_DISTRICT_ERROR =
  "GET_CURRENT_CITY_DISTRICT_ERROR";
export const GET_NEARBY_DISTRICT_SUCCESS = "GET_NEARBY_DISTRICT_SUCCESS";
export const GET_LOCATION_STATION_SUCCESS = "GET_LOCATION_STATION_SUCCESS";
export const GET_STATION_RANKING_REQUESTED = "GET_STATION_RANKING_REQUESTED";
export const GET_STATION_RANKING_SUCCESS = "GET_STATION_RANKING_SUCCESS";
export const GET_STATION_RANKING_ERROR = "GET_STATION_RANKING_ERROR";
export const GET_CITIES_REQUESTED = "GET_CITIES_REQUESTED";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const GET_CITIES_ERROR = "GET_CITIES_ERROR";

/** END NEARBY ACTION TYPES */

/** BEGIN HISTORY ACTION TYPES */
export const SAVE_FROM_DATE_AND_TO_DATE = "SAVE_FROM_DATE_AND_TO_DATE";
/** BEGIN HISTORY ACTION TYPES */
