export const SHOW_ALL_LOCATIONS = 'SHOW_ALL_LOCATIONS'
export const UPDATE_SPIN_STATE = 'UPDATE_SPIN_STATE'

export const GET_LOCATION_RECORDS_SUCCESS = 'GET_LOCATION_RECORDS_SUCCESS'
export const GET_LOCATION_RECORDS_ERROR = 'GET_LOCATION_RECORDS_ERROR'
export const STORE_MAP_DATA = 'STORE_MAP_DATA'

export const GET_AIR_DATA_SUCCESS = 'GET_AIR_DATA_SUCCESS'
export const GET_LOCATION_DETAIL_SUCCESS = 'GET_LOCATION_DETAIL_SUCCESS'
export const GET_LOCATION_DETAIL_ERROR = 'GET_LOCATION_DETAIL_ERROR'